#!/bin/bash
set -e

export GAUCHE_KEYWORD_IS_SYMBOL=1

mkdir -p /home/gauche
cd /home/gauche
rm -rf Gauche && git clone https://github.com/shirok/Gauche.git
(cd Gauche && ./DIST gen)

echo "#############################################################"
echo "#"
echo "#  Core Build with released Gauche"
echo "#"
echo "#"
cd /home/gauche
rm -rf Gauche-build
mkdir Gauche-build
cd Gauche-build
../Gauche/configure --prefix=/usr && make -j && make -s check && make install && make -s install-check

echo "#############################################################"
echo "#"
echo "#  Core Build with self"
echo "#"
echo "#"
cd /home/gauche
cd Gauche
gauche-config --reconfigure | sh && make -j && make -s check && make install && make -s install-check

echo "#############################################################"
echo "#"
echo "#  Gauche-gl"
echo "#"
echo "#"
cd /home/gauche
rm -rf Gauche-gl
git clone https://github.com/shirok/Gauche-gl.git
cd Gauche-gl 
./DIST gen
./configure && make -j && make -s check

echo "#############################################################"
echo "#"
echo "#  Gauche-gtk2"
echo "#"
echo "#"
cd /home/gauche
git clone https://github.com/shirok/Gauche-gtk2.git
cd Gauche-gtk2
./DIST gen
./configure
make stubs
make -j

echo "#############################################################"
echo "#"
echo "#  Gauche-dbd-mysql"
echo "#"
echo "#"
service mysql start
cd /home/gauche
git clone https://github.com/kahua/Gauche-dbd-mysql.git
cd Gauche-dbd-mysql
./DIST gen
./configure
make -j
mysql < /scripts/mysql-setup.sql
make -s check
service mysql stop

