#!/bin/bash
set -e

mkdir -p /home/gauche
cd /home/gauche
rm -rf Gauche && git clone https://github.com/shirok/Gauche.git
(cd Gauche && ./DIST gen)

echo "#############################################################"
echo "#"
echo "#  Core Build with released Gauche"
echo "#"
echo "#"
cd /home/gauche
rm -rf Gauche-build
mkdir Gauche-build
cd Gauche-build
../Gauche/configure --prefix=/usr && make -j && make -s check && make install && make -s install-check

echo "#############################################################"
echo "#"
echo "#  Core Build with self"
echo "#"
echo "#"
cd /home/gauche
cd Gauche
gauche-config --reconfigure | sh && make -j && make -s check && make install && make -s install-check

echo "#############################################################"
echo "#"
echo "#  Gauche-gl"
echo "#"
echo "#"
cd /home/gauche
rm -rf Gauche-gl
git clone https://github.com/shirok/Gauche-gl.git
cd Gauche-gl 
./DIST gen
./configure && make -j && make -s check


