#!/bin/bash
set -e

export GAUCHE_KEYWORD_IS_SYMBOL=1

mkdir -p /home/gauche

. /scripts/core.sh
. /scripts/gauche-gl.sh
. /scripts/wiliki.sh
. /scripts/gauche-gtk2.sh
. /scripts/gauche-text-kakasi.sh
. /scripts/gauche-mecab.sh
. /scripts/gauche-dbd-mysql.sh
# it has test problem atm
# . /scripts/gauche-dbd-mysql3.sh

